### ISSUE TITLE
META: Clean up the build directory in release mode

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#1308]
All packages should clean up their outputs that aren't required for deployment, at least in --release mode. 

This issue will track the status of each:

* [x] `.module` and `.sum` files should be deleted by build_modules
* [x] `.dart` files should be deleted by build_web_compilers
* [x] `.ng_placeholder` files should be deleted by angular
* [x] `.js[.map]` files in the sdk should be deleted by ?
* [x] `.scss` and `.sass` files should be deleted by sass_builder
* [x] Extra dart2js outputs (`.js.deps, .js.tar.gz`, etc) should be deleted by build_web_compilers. This is a little different as it has to do more with just not extracting some of the files from the archive.
* [x] https://github.com/dart-lang/build/issues/1348

**Comment by jakemac53** [comment]
cc @natebosch @kevmoo @matanlurey 

This could be considered blocked on https://github.com/dart-lang/build/issues/1284

**Comment by natebosch** [comment]
@matanlurey - you'd leave the template HTML files in the output directory for release mode? We plan on removing `.dart` files from the output in release mode...

**Comment by natebosch** [comment]
Waiting on a release of Angular and Sass builder but the changes are in.

Only remaining issue is the `.js` files from the SDK

**Comment by jakemac53** [comment]
Random hacky but "safe" (for now) idea for the SDK js files:

The build_web_compilers|entrypoint builder could have a top level boolean field `dartdevcIsUsed` which defaults to false. It would get toggled to true inside the constructor of the builder itself, if the `BuilderOptoins` have dartdevc configured as the compiler.

The cleanup builder which deletes these files would read that top level boolean to determine if it can or cannot clean up the SDK files.

The obvious problem is if we moved to a more parallelized model for builds where we spawn builders in separate isolates or processes, then this would fall apart.

**Comment by natebosch** [comment]
I'd hope to avoid communicating with global state like that. It's an anti-pattern that we want builder authors to avoid so we should model better practices.

What happens when we toggle back to a non-release build? I don't know if we'd correctly invalidate the builder because none of it's inputs will have changed.

**Comment by jakemac53** [comment]
>I'd hope to avoid communicating with global state like that. It's an anti-pattern that we want builder authors to avoid so we should model better practices.

Definitely agree I just don't have any other solutions I can think of that aren't equally bad.

> What happens when we toggle back to a non-release build? I don't know if we'd correctly invalidate the builder because none of it's inputs will have changed.

Good point, back to the drawing board!

**Comment by jakemac53** [comment]
Talked a bit about this with @natebosch and we think the solution will be to create a builder which always cleans up these sdk files in release mode, which does what most people want.

If people configure `dartdevc` as their release compiler, they will need to add in a global configuration override to disable this builder (blocked on https://github.com/dart-lang/build/issues/1370).

To mitigate confusion, we can add custom error handling when we see a missing `dart_sdk` module, which tells you to go disable this builder (and gives you the corresponding build.yaml config to do so).

**Comment by jakemac53** [comment]
We have done everything we are going to do here, I think there is still some amount of leftover js/sourcemap files from the sdk but its greatly reduced now.
