### ISSUE TITLE
Get clean on Dart2

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1482]
- [x] Land latest pub in SDK - https://dart-review.googlesource.com/c/sdk/+/56292
- [x] Get a new pkg:watcher out - 0.9.7+8
- [x] Publish SDK w/ https://dart-review.googlesource.com/c/sdk/+/56292
    - should be in -dev.58
- [x] Fix YamlMap convert error w/ build_config - https://github.com/dart-lang/build/issues/1293
- [x] build_web_compilers issue: https://github.com/dart-lang/build/issues/1487
- [x] build_runner - https://github.com/dart-lang/build/issues/1488
- [x] build_web_compilers - https://github.com/dart-lang/build/issues/1513

**Comment by natebosch** [comment]
Dupe of #1293

**Comment by kevmoo** [comment]
Humor the PM – I'll track this...

**Comment by kevmoo** [comment]
Sample build running now that #1293 is fixed - https://travis-ci.org/dart-lang/build/builds/383404287

**Comment by jakemac53** [comment]
All the checkboxes above are checked off now - rerunning the build to see if we have issues still

**Comment by kevmoo** [comment]
Woo hoo!

**Comment by jakemac53** [comment]
Looks like some failing e2e tests still so we can leave this open, but at least all the unit tests are passing now so that is good :)

**Comment by kevmoo** [comment]
Woo hoo!

**Comment by natebosch** [comment]
Everything seems to pass for me now.
