### ISSUE TITLE
Bundle breaking changes for build_runner 0.7.0

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#628]
These are up for discussion. Collecting them all here so we don't forget something before publishing.

- [x] Drop `PackageNode.dependencyType`.  Nothing reads this field. We could potentially use it to set up fewer directory watchers, but we aren't today.
- [x] Drop `PackageNode.version`. Nothing reads this field.
- [x] Drop `PackageGraph.orderedDependencies` and `PackageGraph.dependentsOf` - We want most use cases for these to shift into `createBuildActions` and stuff inside `build_runner` can use `stronglyConnectedComponents`.
- [x] Stop exporting `InputSet` - shouldn't be any use case
- [x] Stop exporting `BuildAction` - we want `BuilderApplication` to replace this.
- [x] Drop `PackageNode.includes` and `PackageNode.excludes`.
- [x] Add `PackageNode.isRoot` - this would be breaking if we want to add assertions that the PackageGraph has exactly one node reporting `isRoot = true` at `PackageGraph.root`.
- [x] Set minimun SDK to 2.0.0: #645 
- [x] Remove `writeToCache` - #647 
- [x] Update to latest `build_barback` to pick up #643 
- [x] Add a whitelist to the directories that can be considered sources: #666

**Comment by jakemac53** [comment]
I would argue that we should consider not dropping `dependencyType` and `version`, and instead start actually using them to speed up startup.

**Comment by natebosch** [comment]
How would we use `version`?

**Comment by jakemac53** [comment]
I didn't realize how much code we have surrounding this actually - go ahead and delete the version/dependency type

**Comment by natebosch** [comment]
I think we've hit all the breaking changes. A quick scan through the dartdoc looks like we've got it where we want for now - at least for the public interfaces
